### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by DmitriiDenisov** [DmitriiDenisov/telegram_weather_bot#1]
- [x] Disable daily notifications
- [x] Add persistent queue
- [x] Bug fix with sending skipped jobs after restarting Bot
- [x] Put API request and forecast for everyday notifications
- [x] Add two buttons: forecast 5 days / 10 days
- [x] Personalised inline keyboards 
- [x] Fix bug for inline Keyboard when inline keyboard is global variable for all users
- [x] Instead of global variable with storage move to PicklePersistence
- [x] Add multiple buttons for notifications
- [x] Add multiple choice for notifications
- [x] Make keyboard persistent 
- [x] Redo handlers architecture in order to make notifications menu independent 
- [x] Add geo button with start function
- [x] Remove tokens and keys
- [x] Remove from print "Loading formatted geocoded file..."
- [x] Add typing for new location. Need to add ConvHandler here 
- [x] Redo architecture and put everything under ConversationHandler (cancelled because it won't work after rebooting of bot for existing users) 
- [ ] Add new detailed menu with notifications
- [x] After reboot of server/bot show user keyboard (think if it is possible without triggers)
- [x] Create error function that will alway return main keyboard
- [x] Fix bug with condition 'if datetime.now() > t', need to add awareness
- [x] Add button for sending location with telegram.KeyboardButton
- [x] Request location coords with OpenWeather API
- [x] After changing location update notifications
- [x] Switch current weather to One Call API with exclude=daily,hourly,minutely (not necessary) 
- [x] Add emoji 😀 
- [x] Create separate file for constants
- [ ] Как передавать в handler доп параметры 
- [ ] Error in inline part
- [ ] Logging
